### ISSUE TITLE
Collision of Eel helper path with form builder

### ISSUE THREAD

**Issue by Sebobo** [neos/form-fusionrenderer#16]
This package provides the Eel helper:

  `'Neos.Form': 'Neos\Form\FusionRenderer\Eel\Helper\FormHelper'`

and the form builder package defines: 

  `Neos.Form.Builder.Node: 'Neos\Form\Builder\Fusion\Helper\NodeHelper'`

Which causes an error in Neos 4.3 that the `FormHelper` cannot be accessed as array.

**Comment by bwaidelich** [comment]
@Sebobo 

>  the form builder package defines: Neos.Form.Builder.Node [...]

Not yet - only with: https://github.com/neos/form-builder/pull/42 (WIP)

**Comment by Sebobo** [comment]
@bwaidelich Yes, thanks for linking this correctly.

But the correct and reliable solution would be to use the full package name for the helper in this package right?
Instead of just `Neos.Form` it should be `Neos.Form.FusionRenderer`

**Comment by bwaidelich** [comment]
> But the correct and reliable solution would be to use the full package name

Yes, good point. But, in addition, the Eel helper resolution could maybe more resilient and resolve longer matches first

**Comment by bwaidelich** [comment]
Can someone please verify #17 quickly so I can release a bugfix version

**Comment by Sebobo** [comment]
On it
