### ISSUE TITLE
Exception thrown on form render 

### ISSUE THREAD

**Issue by bweinzierl** [neos/form-fusionrenderer#3]
An Exception is thrown as soon as i switch from default preset to FusionPreset in the From Editor (Neos Backend)

".../Packages/Neos/Neos.Fusion/Resources/Private/Fusion" is no directory.

I tracked it back to $formRuntime->render(); inside of FormImplementation->evaluate()

**Comment by bwaidelich** [comment]
I wonder why it expects the package to be installed in `Packages/Neos` - is it installed there? It should be in `Packages/Application` by default

**Comment by bweinzierl** [comment]
It is installed in the default location (Packages/Application). That is what puzzles me to. If your test-setup works (with fusion preset selected in node) i will debug it further... than it has to be something in my installation.

**Comment by bweinzierl** [comment]
I looked again and there is a wrong path specified in:
FusionFormRenderer.php Line 51

`FLOW_PATH_PACKAGES . 'Neos/Neos.Fusion/Resources/Private/Fusion',`

should be:

`FLOW_PATH_PACKAGES . 'Application/Neos.Fusion/Resources/Private/Fusion',`

**Comment by bwaidelich** [comment]
@bweinzierl OK, interesting.. In my case (dev-master) the Fusion package is installed in `Packages/Neos`. I'll look into it
