### ISSUE TITLE
Formbuilder throws exception when selecting fusion preset

### ISSUE THREAD

**Issue by bweinzierl** [neos/form-fusionrenderer#4]
Steps to recreate:
Create a nodebased form and then select the fusion preset in the property inspector. Press apply.

Exception Thrown:
`Argument 3 passed to Neos\Form\FusionRenderer\Eel\Helper\FormHelper_Original::translate() must be of the type string, null given, called in /project/source/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Form_FusionRenderer_Eel_Helper_FormHelper.php on line 79`

Thats because in line 72 "$defaultValue = $element->getLabel();" returns null.

**Comment by bwaidelich** [comment]
I still can't reproduce this with `dev-master`, but I change this anyways to support `null`
